import 'globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.cdnfonts.com/css/helvetica-neue-5" rel="stylesheet" />
      </head>
      <body>{children}</body>
    </html>
  )
}
